/**
 * Curated Fallback Catalog for SUNFLIX
 * Guarantees that movies & TV shows always render smoothly with high quality posters,
 * backdrops, ratings, synopses, and working trailer links if network APIs fail or are blocked.
 */

export const FALLBACK_MOVIES = [
    {
        id: 'tt15398776',
        imdbID: 'tt15398776',
        title: 'Oppenheimer',
        name: 'Oppenheimer',
        poster_path: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=800&auto=format&fit=crop',
        backdrop_path: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop',
        vote_average: 8.9,
        imdbRating: '8.9',
        release_date: '2023',
        overview: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.',
        media_type: 'movie',
        type: 'movie',
        genre: 'Biography, Drama, History',
        director: 'Christopher Nolan',
        actors: 'Cillian Murphy, Emily Blunt, Matt Damon',
        rated: 'R',
        runtime: '180 min',
        videoId: 'uYPbbksJxIg'
    },
    {
        id: 'tt15239678',
        imdbID: 'tt15239678',
        title: 'Dune: Part Two',
        name: 'Dune: Part Two',
        poster_path: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop',
        backdrop_path: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1200&auto=format&fit=crop',
        vote_average: 8.8,
        imdbRating: '8.8',
        release_date: '2024',
        overview: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
        media_type: 'movie',
        type: 'movie',
        genre: 'Action, Adventure, Sci-Fi',
        director: 'Denis Villeneuve',
        actors: 'Timothée Chalamet, Zendaya, Rebecca Ferguson',
        rated: 'PG-13',
        runtime: '166 min',
        videoId: 'Way9Dexny3w'
    },
    {
        id: 'tt9362722',
        imdbID: 'tt9362722',
        title: 'Spider-Man: Across the Spider-Verse',
        name: 'Spider-Man: Across the Spider-Verse',
        poster_path: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?q=80&w=800&auto=format&fit=crop',
        backdrop_path: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=1200&auto=format&fit=crop',
        vote_average: 8.7,
        imdbRating: '8.7',
        release_date: '2023',
        overview: 'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its existence.',
        media_type: 'movie',
        type: 'movie',
        genre: 'Animation, Action, Adventure',
        director: 'Joaquim Dos Santos, Kemp Powers',
        actors: 'Shameik Moore, Hailee Steinfeld, Oscar Isaac',
        rated: 'PG',
        runtime: '140 min',
        videoId: 'cqGjhVJWtEg'
    },
    {
        id: 'tt10366206',
        imdbID: 'tt10366206',
        title: 'John Wick: Chapter 4',
        name: 'John Wick: Chapter 4',
        poster_path: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=800&auto=format&fit=crop',
        backdrop_path: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=1200&auto=format&fit=crop',
        vote_average: 8.4,
        imdbRating: '8.4',
        release_date: '2023',
        overview: 'John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy.',
        media_type: 'movie',
        type: 'movie',
        genre: 'Action, Crime, Thriller',
        director: 'Chad Stahelski',
        actors: 'Keanu Reeves, Donnie Yen, Bill Skarsgård',
        rated: 'R',
        runtime: '169 min',
        videoId: 'yjRHZEUamCc'
    },
    {
        id: 'tt6843046',
        imdbID: 'tt6843046',
        title: 'RRR',
        name: 'RRR',
        poster_path: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=800&auto=format&fit=crop',
        backdrop_path: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?q=80&w=1200&auto=format&fit=crop',
        vote_average: 8.5,
        imdbRating: '8.5',
        release_date: '2022',
        overview: 'A tale of two legendary revolutionaries and their journey far away from home before they started fighting for their country in the 1920s.',
        media_type: 'movie',
        type: 'movie',
        genre: 'Action, Drama, Sci-Fi',
        director: 'S.S. Rajamouli',
        actors: 'N.T. Rama Rao Jr., Ram Charan, Ajay Devgn',
        rated: 'PG-13',
        runtime: '187 min',
        videoId: 'NgBoT66qH94'
    },
    {
        id: 'tt0111161',
        imdbID: 'tt0111161',
        title: 'The Shawshank Redemption',
        name: 'The Shawshank Redemption',
        poster_path: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=800&auto=format&fit=crop',
        backdrop_path: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=1200&auto=format&fit=crop',
        vote_average: 9.3,
        imdbRating: '9.3',
        release_date: '1994',
        overview: 'Over the course of several years, two convicts form a friendship, seeking consolation and eventual redemption through basic compassion.',
        media_type: 'movie',
        type: 'movie',
        genre: 'Drama',
        director: 'Frank Darabont',
        actors: 'Tim Robbins, Morgan Freeman',
        rated: 'R',
        runtime: '142 min',
        videoId: '6hB3S9bIaco'
    },
    {
        id: 'tt0816692',
        imdbID: 'tt0816692',
        title: 'Interstellar',
        name: 'Interstellar',
        poster_path: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800&auto=format&fit=crop',
        backdrop_path: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=1200&auto=format&fit=crop',
        vote_average: 8.7,
        imdbRating: '8.7',
        release_date: '2014',
        overview: 'When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.',
        media_type: 'movie',
        type: 'movie',
        genre: 'Adventure, Drama, Sci-Fi',
        director: 'Christopher Nolan',
        actors: 'Matthew McConaughey, Anne Hathaway, Jessica Chastain',
        rated: 'PG-13',
        runtime: '169 min',
        videoId: 'zSWdZVtXT7E'
    },
    {
        id: 'tt0133093',
        imdbID: 'tt0133093',
        title: 'The Matrix',
        name: 'The Matrix',
        poster_path: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=800&auto=format&fit=crop',
        backdrop_path: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop',
        vote_average: 8.7,
        imdbRating: '8.7',
        release_date: '1999',
        overview: 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.',
        media_type: 'movie',
        type: 'movie',
        genre: 'Action, Sci-Fi',
        director: 'Lana Wachowski, Lilly Wachowski',
        actors: 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss',
        rated: 'R',
        runtime: '136 min',
        videoId: 'vKQi3bBA1y8'
    }
];

export const FALLBACK_TV = [
    {
        id: 'tt0903747',
        imdbID: 'tt0903747',
        title: 'Breaking Bad',
        name: 'Breaking Bad',
        poster_path: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
        backdrop_path: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1200&auto=format&fit=crop',
        vote_average: 9.5,
        imdbRating: '9.5',
        release_date: '2008',
        overview: 'A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student in order to secure his family\'s financial future.',
        media_type: 'tv',
        type: 'series',
        genre: 'Crime, Drama, Thriller',
        number_of_seasons: 5,
        number_of_episodes: 62,
        videoId: 'HhesaQXLuRY'
    },
    {
        id: 'tt0944947',
        imdbID: 'tt0944947',
        title: 'Game of Thrones',
        name: 'Game of Thrones',
        poster_path: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=800&auto=format&fit=crop',
        backdrop_path: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=1200&auto=format&fit=crop',
        vote_average: 9.2,
        imdbRating: '9.2',
        release_date: '2011',
        overview: 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.',
        media_type: 'tv',
        type: 'series',
        genre: 'Action, Adventure, Drama',
        number_of_seasons: 8,
        number_of_episodes: 73,
        videoId: 'gcTkNV5Vg1E'
    },
    {
        id: 'tt4574334',
        imdbID: 'tt4574334',
        title: 'Stranger Things',
        name: 'Stranger Things',
        poster_path: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=800&auto=format&fit=crop',
        backdrop_path: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?q=80&w=1200&auto=format&fit=crop',
        vote_average: 8.7,
        imdbRating: '8.7',
        release_date: '2016',
        overview: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.',
        media_type: 'tv',
        type: 'series',
        genre: 'Drama, Fantasy, Horror',
        number_of_seasons: 4,
        number_of_episodes: 34,
        videoId: 'b9EkMc79ZSU'
    }
];

export function getFallbackCatalog(keyOrArray) {
    if (typeof keyOrArray === 'string' && (keyOrArray.includes('Tv') || keyOrArray.includes('tv') || keyOrArray.includes('Originals'))) {
        return FALLBACK_TV;
    }
    return FALLBACK_MOVIES;
}

export default {
    FALLBACK_MOVIES,
    FALLBACK_TV,
    getFallbackCatalog
};
